import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer/Footer'
import Navbar from '../components/Navbar/Navbar'
import styles from '../styles/Home.module.css'
import HypeSelling from './HypeSelling'
import ShippingBuyer from './ShippingBuyer'
import ShippingSeller from './ShippingSeller'
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
       

        <meta name="description" content="Generated by create next app" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <div>
        <HypeSelling />

       </div>
       
    </div>
  )
}
